import { useState, useEffect, useMemo } from 'react'
import { EarthquakeEvent } from '../types'
import { useStore } from '../store'

// In-memory cache so years aren't re-fetched as the time window moves.
// Exported so the timeline can render ticks for all loaded years, not just
// the current window.
export const yearCache = new Map<number, EarthquakeEvent[]>()

function yearOf(ms: number): number {
  return new Date(ms).getUTCFullYear()
}

/**
 * Loads earthquake data for the years covered by the current time window,
 * filters by the active magnitude/depth settings, and returns the visible events.
 *
 * Data is fetched from /data/YYYY.json — generated by `sp-export` in the pipeline.
 * Missing years (pre-catalog, future) are cached as empty arrays so they aren't
 * re-requested on every render.
 */
export function useEarthquakeData(): EarthquakeEvent[] {
  const { windowStart, windowDuration, minMagnitude, maxDepth } = useStore()
  const windowEnd = windowStart + windowDuration

  const startYear = yearOf(windowStart)
  const endYear   = yearOf(windowEnd)

  // Incrementing this triggers a re-filter when new year data finishes loading
  const [loadTick, setLoadTick] = useState(0)

  useEffect(() => {
    const missing: number[] = []
    for (let y = startYear; y <= endYear; y++) {
      if (!yearCache.has(y)) missing.push(y)
    }
    if (missing.length === 0) return

    Promise.all(
      missing.map(y =>
        fetch(`/data/${y}.json`)
          .then(r => r.ok ? r.json() : [])
          .then((rows: (number | string)[][]) => {
            yearCache.set(
              y,
              rows.map(([time, lat, lon, depth_km, magnitude, place]) => ({
                time:      time      as number,
                lat:       lat       as number,
                lon:       lon       as number,
                depth_km:  depth_km  as number,
                magnitude: magnitude as number,
                place:     (place as string) || undefined,
              })),
            )
          })
          .catch(() => yearCache.set(y, [])),
      ),
    ).then(() => setLoadTick(t => t + 1))
  }, [startYear, endYear])

  return useMemo(() => {
    const result: EarthquakeEvent[] = []
    for (let y = startYear; y <= endYear; y++) {
      for (const e of yearCache.get(y) ?? []) {
        if (
          e.time      >= windowStart &&
          e.time      <  windowEnd &&
          e.magnitude >= minMagnitude &&
          e.depth_km  <= maxDepth
        ) {
          result.push(e)
        }
      }
    }
    return result
  }, [loadTick, windowStart, windowEnd, minMagnitude, maxDepth, startYear, endYear])
}
