bucket       = "glolabs-tf-state"
use_lockfile = true
kms_key_id   = "arn:aws:kms:us-east-1:634157847749:key/db327299-919f-4ebb-82f3-f3a3caac2c56"
role_arn     = "arn:aws:iam::634157847749:role/tf-seismicplanet"
region       = "us-east-1"
encrypt      = true
key          = "seismicplanet/prod/terraform.tfstate"
