apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: seismicplanet
  annotations:
    # Replace with the value of `terraform output pipeline_role_arn`
    eks.amazonaws.com/role-arn: arn:aws:iam::634157847749:role/seismicplanet-pipeline
